In [23]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from ml_atmospheric_emission.config import PATH_RAW, PATH_INTERIM
from ml_atmospheric_emission.dataset import load_raw, rename_columns, filter_rows,round_float_columns

In [26]:
ds = load_raw()
#ds.info()
ds

,Unnamed: 0,nn_ok_smog,nn_score_smog,int_sd,int_med,306-AIT-004-2,306-AIT-004-5,306FE002-AI001-R,406-AI-004-2,406-AI-004-4,406-AIT-001
0,2026-10-13 08:30:00,0.0,0.000677,8.000000,10.586340,58.261623,151.767673,2.979544,77.782647,185.112225,3.404892
1,2026-10-13 08:25:00,0.0,0.000978,9.000000,11.835665,56.460173,141.337282,1.841905,73.699460,203.883847,2.368845
2,2026-10-13 08:20:00,0.0,0.001279,3.000000,5.334077,54.422600,137.762843,2.409530,63.983227,189.094398,3.879804
3,2026-10-13 08:15:00,0.0,0.001580,0.000000,2.481736,54.517484,132.692097,2.927432,62.986229,165.927663,7.773820
4,2026-10-13 08:10:00,0.0,0.001881,0.000000,0.683143,49.166838,143.008684,2.082216,73.792445,161.779503,4.146081
...,...,...,...,...,...,...,...,...,...,...,...
82177,2026-01-01 00:25:00,0.0,NaN,0.076180,0.005872,198.460668,397.779983,4.123388,239.332557,314.149913,1.195021
82178,2026-01-01 00:20:00,0.0,NaN,0.082301,0.006507,196.443690,413.436480,4.328994,242.022713,313.450450,0.826593
82179,2026-01-01 00:15:00,0.0,NaN,0.088422,0.007141,182.839817,408.747242,3.436024,229.542205,330.503377,0.661848
82180,2026-01-01 00:10:00,0.0,NaN,0.094542,0.007775,224.746664,410.036339,4.425347,231.303528,323.707047,1.499174
82181,2026-01-01 00:05:00,0.0,NaN,0.096796,0.008006,208.748061,422.948386,3.134054,227.211458,318.310547,1.000614

In [27]:
ds = rename_columns(ds)
ds = round_float_columns(ds)
ds = filter_rows(ds)
ds

,Data,nn_score_smog,int_sd,int_med,306-AIT-004-2,306-AIT-004-5,306FE002-AI001-R,406-AI-004-2,406-AI-004-4,406-AIT-001
0,2026-10-13 08:30:00,0.001,8.0,10.586,58.262,151.768,2.980,77.783,185.112,3.405
1,2026-10-13 08:25:00,0.001,9.0,11.836,56.460,141.337,1.842,73.699,203.884,2.369
2,2026-10-13 08:20:00,0.001,3.0,5.334,54.423,137.763,2.410,63.983,189.094,3.880
3,2026-10-13 08:15:00,0.002,0.0,2.482,54.517,132.692,2.927,62.986,165.928,7.774
4,2026-10-13 08:10:00,0.002,0.0,0.683,49.167,143.009,2.082,73.792,161.780,4.146
...,...,...,...,...,...,...,...,...,...,...
15479,2026-08-20 14:35:00,1.000,152.0,149.863,67.240,173.400,7.643,42.162,176.990,0.852
15480,2026-08-20 14:30:00,1.000,152.0,148.253,68.476,174.032,8.987,40.868,176.775,0.555
15481,2026-08-20 14:25:00,1.000,152.0,144.478,66.290,181.367,6.485,41.679,174.437,0.919
15482,2026-08-20 14:20:00,1.000,152.0,155.969,67.433,186.557,7.291,45.751,178.031,1.036
15483,2026-08-20 14:15:00,1.000,152.0,153.134,71.445,183.992,7.277,43.072,178.567,1.008

In [28]:
ds.to_csv(PATH_INTERIM, index=False)
ds.info()

<class 'pandas.DataFrame'>
Index: 15074 entries, 0 to 15483
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Data              15074 non-null  datetime64[us]
 1   nn_score_smog     15074 non-null  float64
 2   int_sd            15046 non-null  float64
 3   int_med           15046 non-null  float64
 4   306-AIT-004-2     15041 non-null  float64
 5   306-AIT-004-5     15041 non-null  float64
 6   306FE002-AI001-R  15036 non-null  float64
 7   406-AI-004-2      15044 non-null  float64
 8   406-AI-004-4      15044 non-null  float64
 9   406-AIT-001       15042 non-null  float64
dtypes: datetime64[us](1), float64(9)
memory usage: 1.3 MB